var stateAndContants = new function () {
    this.SUCCESS_COLOR = "#66cc66";
    this.FAILURE_COLOR = "#ff6666";
    this.WARNING_COLOR = "#e59814";
    this.passwordsMatch = false;
    this.passwordStrongEnough = false;
    this.loginAvailable = false;
    this.peselCorrect = false;
    this.typingTimer = undefined;
    this.doneTypingInterval = 500;
    this.loginDiv = undefined;
    this.passDiv = undefined;
    this.passRepeatDiv = undefined;
    this.passMessage = undefined;
    this.repeatPassMessage = undefined;
    this.loginMessage = undefined;
    this.sexMessage = undefined;
    this.birthdateMessage = undefined;
};